### ISSUE TITLE
From clinicians: Real world use cases please

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/ddd#24]
... for dynamic triggers 

/cc @gabpoll @drcjar @michaeledwardmarks

**Comment by rossjones** [comment]
This issue was moved to openhealthcare/cedar#12

**Comment by GabPoll** [comment]
Thanks for moving this over @rossjones!

**Comment by rossjones** [comment]
No problem, didn't want to lose anything and found a magic tool to do it for me :)
