### ISSUE TITLE
Categories

### ISSUE THREAD

**Issue by rossjones** [openhealthcare/ddd#7]
It should be possible to pull categories from an external source.

Use-case: 
OPAL has a list of ID specific medication, it would be handy if D<sup>3</sup> had access to those fields.  We could probably get them from elsewhere, but per-installation we don't want to show irrelevant data as options for rules.

**Comment by davidmiller** [comment]
So, this has come up elsewhere - the format for having a "version" of a taxonomy list somewhere and know what version you're using, and "release" a new version.

This is a problem syncing various lists with e.g. elCID.

Also - what you'll want is to start from a version of a base list, and then apply local patches - additions, removals etc.

**Comment by rossjones** [comment]
Should this be a glossolalialossia ticket?

**Comment by davidmiller** [comment]
I'm not sure you'd want to go across the network for it...  ?

The data is currently stored in flies like https://github.com/openhealthcare/elcid/blob/master/data/lookuplists/lookuplists.json

OPAL has management commands to load them
https://github.com/openhealthcare/opal/blob/master/opal/management/commands/dump_lookup_lists.py
https://github.com/openhealthcare/opal/blob/master/opal/management/commands/load_lookup_lists.py

I think that what you want is a versioned packaging format for the json and the ability for clinical experts to raise issues, add, remove from taxonomies.

I have flirted with the idea of making the format friendlier ( ?Yaml) and splitting them into separate repositories e.g. one for elCID. 
Hook travis up to a linter for the data and grant write access + issue tracker to clinical stafff, pin the requirement at a tag. 

Or something - am mostly braindumping.

Would love to have a better way to manage these.

**Comment by rossjones** [comment]
This issue was moved to openhealthcare/cedar#24
